version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest-browsers

    working_directory: ~/vialer-js

    steps:
      - checkout
      - restore_cache:
          key: v5-{{ checksum "package-lock.json" }}

      - run:
          command:
            npm ci

      - save_cache:
          key: v5-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

      - run: cp .vialer-jsrc.example .vialer-jsrc
      - run: npm run test
